# Generated by Django 4.1.13 on 2024-08-10 06:38

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_homework_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
